### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by ezequielvictor** [hajipy/embedded-queue#50]
Do I have to shutdown every queue?

I tried o use just one instance of a created queue but each time that i use, it`s increase on call on queue.on(Event.Complete)

![image](https://user-images.githubusercontent.com/25374556/200306626-a5cf82e2-f138-4774-b732-f5c2e7de90e4.png)

as I don't need to use anything in the event complete, I just removed the listener and for now it solves my problem.

**Comment by hajipy** [comment]
@ezequielvictor 
Queue inherits from Node.js' EventEmitter and does not implement Queue.on itself.
Since it is unlikely that the Node.js EventEmitter is leaking memory, it seems more likely that there is a problem with the calling code.
Queue.on should be called only once, but are you calling it many times?

**Comment by ezequielvictor** [comment]
oh, yeah, so that's my fault, I didn't think that way.
Thanks for the quick answer!
